services:
  app:
    container_name: ${CONTAINER_NAME}
    # Utiliza a imagem devcontainer local
    image: ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
    pull_policy: missing
    # Utiliza a imagem devcontainer com adições, a linha de cima deve ser comentada
    # build:
      # context: ..
      # dockerfile: .devcontainer/Dockerfile
      # args:
      #   HOST_UID: ${HOST_UID:-1000}
      #   HOST_GID: ${HOST_GID:-1000}
    environment:
      - TZ=America/Sao_Paulo
    restart: unless-stopped
    volumes:
      - ..:${PROJECT_FOLDER}:cached
    command: sleep infinity